export const ADD_ITEM = 'ADD_ITEM'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_ITEM = 'DELETE_ITEM'
export const DELETE_TODO = 'DELETE_TODO'
export const UPDATE_HEADER = 'UPDATE_HEADER'
export const UPDATE_ITEM = 'UPDATE_ITEM'
